# Generated by Django 5.2.7 on 2025-10-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taoism_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TK_Videos',
            new_name='TK_Video',
        ),
    ]
