# Generated by Django 5.2.7 on 2025-10-25 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taoism_site', '0003_alter_tk_video_options_remove_tk_video_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tk_video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
