# Generated by Django 5.2.7 on 2025-10-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taoism_site', '0004_tk_video_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tk_video',
            name='description',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
