# Generated by Django 5.2.7 on 2025-10-26 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taoism_site', '0005_tk_video_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tk_video',
            name='description',
        ),
        migrations.AlterField(
            model_name='blog_category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tk_video',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
